package com.techwhizer.snsbiosystem.custom_enum;

public enum OperationType {
    ALL, DEFAULT, START, DELETE, UPDATE, CREATE, FETCH,
    PREVIEW, SINGLE_KIT_USAGE, DOWNLOAD_REPORT , CUSTOMER_REPORT,KIT_REPORT, SORTING_LOADING,FROM_LOGIN,FROM_DASHBOARD
}


